language: ruby
rvm:
 - 2.2
addons:
  code_climate:
    repo_token: 449e047a2987971c8ef57257374a4c750434ac9d2c9b5dc61e61ff3a8b8196d1
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
